[variables]
NEXT_PUBLIC_ENV = "${env:NEXT_PUBLIC_ENV}"
NEXT_PUBLIC_SUPABASE_ANON_KEY = "${env:NEXT_PUBLIC_SUPABASE_ANON_KEY}"
NEXT_PUBLIC_SUPABASE_URL = "${env:NEXT_PUBLIC_SUPABASE_URL}"
NEXT_PUBLIC_URL = "${env:NEXT_PUBLIC_URL}"

[phases.setup]
aptPkgs = ['python3', 'make', 'g++', 'libudev-dev']
