create type "public"."chains" as enum ('SOL', 'TRON', 'TON', 'ETH', 'MATIC', 'BASE', 'COSMOS', 'BNB', 'ADA');

alter table "public"."solana_wallets" drop constraint "solana_wallets_pkey";

drop index if exists "public"."solana_wallets_pkey";

alter table "public"."listings" add column "chain" chains not null;

alter table "public"."solana_wallets" add column "id" bigint generated by default as identity not null;

alter table "public"."solana_wallets" alter column "user_id" drop not null;

CREATE UNIQUE INDEX solana_wallets_pkey ON public.solana_wallets USING btree (id);

alter table "public"."solana_wallets" add constraint "solana_wallets_pkey" PRIMARY KEY using index "solana_wallets_pkey";


