create table "public"."listing_banners" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "image_url" text not null,
    "out_url" text,
    "order" smallint,
    "listing_id" bigint
);


alter table "public"."listing_banners" enable row level security;

CREATE UNIQUE INDEX listing_banners_order_key ON public.listing_banners USING btree ("order");

CREATE UNIQUE INDEX listing_banners_pkey ON public.listing_banners USING btree (id);

alter table "public"."listing_banners" add constraint "listing_banners_pkey" PRIMARY KEY using index "listing_banners_pkey";

alter table "public"."listing_banners" add constraint "listing_banners_listing_id_fkey" FOREIGN KEY (listing_id) REFERENCES listings(id) ON UPDATE RESTRICT ON DELETE CASCADE not valid;

alter table "public"."listing_banners" validate constraint "listing_banners_listing_id_fkey";

alter table "public"."listing_banners" add constraint "listing_banners_order_key" UNIQUE using index "listing_banners_order_key";

grant delete on table "public"."listing_banners" to "anon";

grant insert on table "public"."listing_banners" to "anon";

grant references on table "public"."listing_banners" to "anon";

grant select on table "public"."listing_banners" to "anon";

grant trigger on table "public"."listing_banners" to "anon";

grant truncate on table "public"."listing_banners" to "anon";

grant update on table "public"."listing_banners" to "anon";

grant delete on table "public"."listing_banners" to "authenticated";

grant insert on table "public"."listing_banners" to "authenticated";

grant references on table "public"."listing_banners" to "authenticated";

grant select on table "public"."listing_banners" to "authenticated";

grant trigger on table "public"."listing_banners" to "authenticated";

grant truncate on table "public"."listing_banners" to "authenticated";

grant update on table "public"."listing_banners" to "authenticated";

grant delete on table "public"."listing_banners" to "service_role";

grant insert on table "public"."listing_banners" to "service_role";

grant references on table "public"."listing_banners" to "service_role";

grant select on table "public"."listing_banners" to "service_role";

grant trigger on table "public"."listing_banners" to "service_role";

grant truncate on table "public"."listing_banners" to "service_role";

grant update on table "public"."listing_banners" to "service_role";

create policy "Enable read access for all users"
on "public"."listing_banners"
as permissive
for select
to public
using (true);

insert into storage.buckets ("id", "name", "owner", "created_at", "updated_at", "public", "avif_autodetection", "file_size_limit", "allowed_mime_types", "owner_id") values ('listing_banner_icons', 'listing_banner_icons', NULL, 'now()', 'now()', true, false, NULL, NULL, NULL);


