drop policy "Enable read access for all users" on "public"."banners";

drop policy "enable admin access" on "public"."banners";

revoke delete on table "public"."banners" from "anon";

revoke insert on table "public"."banners" from "anon";

revoke references on table "public"."banners" from "anon";

revoke select on table "public"."banners" from "anon";

revoke trigger on table "public"."banners" from "anon";

revoke truncate on table "public"."banners" from "anon";

revoke update on table "public"."banners" from "anon";

revoke delete on table "public"."banners" from "authenticated";

revoke insert on table "public"."banners" from "authenticated";

revoke references on table "public"."banners" from "authenticated";

revoke select on table "public"."banners" from "authenticated";

revoke trigger on table "public"."banners" from "authenticated";

revoke truncate on table "public"."banners" from "authenticated";

revoke update on table "public"."banners" from "authenticated";

revoke delete on table "public"."banners" from "service_role";

revoke insert on table "public"."banners" from "service_role";

revoke references on table "public"."banners" from "service_role";

revoke select on table "public"."banners" from "service_role";

revoke trigger on table "public"."banners" from "service_role";

revoke truncate on table "public"."banners" from "service_role";

revoke update on table "public"."banners" from "service_role";

alter table "public"."banners" drop constraint "banners_drop_url_fkey";

alter table "public"."banners" drop constraint "banners_order_key";

alter table "public"."banners" drop constraint "banners_pkey";

drop index if exists "public"."banners_order_key";

drop index if exists "public"."banners_pkey";

drop table "public"."banners";

create table "public"."airdrop_banners" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "image_url" text not null,
    "title" text,
    "description" text,
    "drop_url" text,
    "out_url" text,
    "order" smallint,
    "drop_url_text" text default 'Earn'::text,
    "out_url_text" text default 'Go'::text
);


alter table "public"."airdrop_banners" enable row level security;

CREATE UNIQUE INDEX banners_order_key ON public.airdrop_banners USING btree ("order");

CREATE UNIQUE INDEX banners_pkey ON public.airdrop_banners USING btree (id);

alter table "public"."airdrop_banners" add constraint "banners_pkey" PRIMARY KEY using index "banners_pkey";

alter table "public"."airdrop_banners" add constraint "banners_drop_url_fkey" FOREIGN KEY (drop_url) REFERENCES airdrops(slug) ON UPDATE RESTRICT ON DELETE SET NULL not valid;

alter table "public"."airdrop_banners" validate constraint "banners_drop_url_fkey";

alter table "public"."airdrop_banners" add constraint "banners_order_key" UNIQUE using index "banners_order_key";

grant delete on table "public"."airdrop_banners" to "anon";

grant insert on table "public"."airdrop_banners" to "anon";

grant references on table "public"."airdrop_banners" to "anon";

grant select on table "public"."airdrop_banners" to "anon";

grant trigger on table "public"."airdrop_banners" to "anon";

grant truncate on table "public"."airdrop_banners" to "anon";

grant update on table "public"."airdrop_banners" to "anon";

grant delete on table "public"."airdrop_banners" to "authenticated";

grant insert on table "public"."airdrop_banners" to "authenticated";

grant references on table "public"."airdrop_banners" to "authenticated";

grant select on table "public"."airdrop_banners" to "authenticated";

grant trigger on table "public"."airdrop_banners" to "authenticated";

grant truncate on table "public"."airdrop_banners" to "authenticated";

grant update on table "public"."airdrop_banners" to "authenticated";

grant delete on table "public"."airdrop_banners" to "service_role";

grant insert on table "public"."airdrop_banners" to "service_role";

grant references on table "public"."airdrop_banners" to "service_role";

grant select on table "public"."airdrop_banners" to "service_role";

grant trigger on table "public"."airdrop_banners" to "service_role";

grant truncate on table "public"."airdrop_banners" to "service_role";

grant update on table "public"."airdrop_banners" to "service_role";

create policy "Enable read access for all users"
on "public"."airdrop_banners"
as permissive
for select
to public
using (true);


create policy "enable admin access"
on "public"."airdrop_banners"
as permissive
for all
to authenticated
using (is_admin(auth.uid()));



